### ISSUE TITLE
Latency Issue

### ISSUE THREAD

**Issue by OutdatedGuy** [OutdatedGuy/Multiplayer-Snake#2]
Facing latency issues for this when deployed on heroku and glitch, as their servers are in USA and client location is far away.

**Comment by Kirteeraj** [comment]
@OutdatedGuy Are you sure the issue is because of the location of the server?  or there might be an optimization issue in the code.

**Comment by OutdatedGuy** [comment]
> @OutdatedGuy Are you sure the issue is because of the location of the server? or there might be an optimization issue in the code.

@Kirteeraj well the code has plenty of room for optimization but the latency issue is certainly because of server location as the data have to travel through many connection, the ping is high just like how you would see in any MMO games when playing on different servers.

**Comment by OutdatedGuy** [comment]
Would have to use backend like `Firebase Cloud Functions` to handle the latency issue by setting project location to `asia-south1`.
